# permissions for end users to edit c2apps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: c2app-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: c2dk-operator
    app.kubernetes.io/part-of: c2dk-operator
    app.kubernetes.io/managed-by: kustomize
  name: c2app-editor-role
rules:
- apiGroups:
  - c2dk.c2cloud.cn
  resources:
  - c2apps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - c2dk.c2cloud.cn
  resources:
  - c2apps/status
  verbs:
  - get
