apiVersion: c2cloud.c2cloud.cn/v1
kind: Event
metadata:
  labels:
    app.kubernetes.io/name: event
    app.kubernetes.io/instance: event-sample
    app.kubernetes.io/part-of: c2dk-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: c2dk-operator
  name: event-sample
spec:
  # TODO(user): Add fields here
