apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: pixiu-localstorage
mountOptions:
  - owner=caoyingjunz
parameters:
  project: pixiu
provisioner: localstorage.csi.caoyingjunz.io
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
