global:
  external_labels:
    env: test
  query_log_file: prometheus.log
  scrape_interval: 15s
  scrape_timeout: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager.kube-prometheus.svc:9093
rule_files:
- /etc/prometheus/prometheus.rules
scrape_configs:
- job_name: kubenernetes-prometheus-server
  static_configs:
  - targets:
    - localhost:9090
  basic_auth: {}
  file_sd_configs: []
- job_name: node
  static_configs: null
  basic_auth:
    password: node@2020
    username: node
  file_sd_configs:
  - files:
    - sd/file/node/*.yaml
    - sd/file/node/*.json
- job_name: test
  static_configs: null
  basic_auth:
    test: test
  file_sd_configs:
  - files:
    - sd/file/%s/*.yamltest
    - sd/file/test/*.json
