global:
  scrape_interval: 15s
  scrape_timeout: 15s
  query_log_file: "prometheus.log"
  external_labels:
    env: test

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - "alertmanager.kube-prometheus.svc:9093"

rule_files:
- /etc/prometheus/prometheus.rules

scrape_configs:
  - job_name: 'kubenernetes-prometheus-server'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: "node"
    basic_auth:
      username: "node"
      password: "node@2020"
    file_sd_configs:
    - files:
      - sd/file/node/*.yaml
      - sd/file/node/*.json