# permissions for end users to view demoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: demo-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubebuilder-operator-demo
    app.kubernetes.io/part-of: kubebuilder-operator-demo
    app.kubernetes.io/managed-by: kustomize
  name: demo-viewer-role
rules:
- apiGroups:
  - test.test.domain
  resources:
  - demoes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - test.test.domain
  resources:
  - demoes/status
  verbs:
  - get
